### ISSUE TITLE
Attempt to encrypt data fails

### ISSUE THREAD

**Issue by Kunal-Attri** [Kunal-Attri/Data-Security-using-Cryptography-and-Steganography#3]
Error is related to AES Encryption in Encrypt.py file
`Traceback (most recent call last):
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\main.py", line 63, in <module>
    main()
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\main.py", line 28, in main
    secure.secure_file(fName)
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\multipledispatch\dispatcher.py", line 435, in __call__
    return func(self.obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\lib\Secure.py", line 16, in secure_file
    f = self.crypt.encrypt_file(f)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\lib\Crypt.py", line 66, in encrypt_file
    enc = self.encrypt(enc, self.key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\lib\Crypt.py", line 33, in encrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\Crypto\Cipher\AES.py", line 228, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\Crypto\Cipher\AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
                             ^^^^^^^^^^^^^^^^
  File "C:\Users\attri\OneDrive\Desktop\check\Data-Security-using-Cryptography-and-Steganography\test\Lib\site-packages\Crypto\Util\_raw_api.py", line 242, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code`

**Comment by Kunal-Attri** [comment]
Resolved with commit #6f5b9d7
